
PROC SORT DATA=INPUT;
	BY SUBJECT ONCOLOGIST REPEAT;
RUN;

PROC MEANS DATA=INPUT NOPRINT;
	VAR VOLUME;
	BY SUBJECT ONCOLOGIST;
	OUTPUT OUT=MEANS MEAN=VOLUME;
RUN;

DATA MEANS;
	SET MEANS;
	REPEAT=ONCOLOGIST;
RUN;

PROC MIXED DATA=MEANS METHOD=TYPE3;
	CLASS SUBJECT ONCOLOGIST;
	MODEL VOLUME = ONCOLOGIST /SOLUTION CL OUTP=PRED2;
	RANDOM SUBJECT;
RUN;

PROC UNIVARIATE DATA=PRED2 NORMAL;
	VAR RESID;
	PROBPLOT RESID /NORMAL(MU=est SIGMA=est);
RUN;

PROC GLM DATA=PRED2;
	CLASS ONCOLOGIST;
	MODEL RESID = ONCOLOGIST;
	MEANS ONCOLOGIST/ HOVTEST=Bartlett;
RUN;


PROC SORT DATA=MEANS;
	BY SUBJECT;
RUN;

PROC MIXED DATA=MEANS METHOD=TYPE3;
	CLASS SUBJECT ONCOLOGIST;
	MODEL VOLUME = ONCOLOGIST /SOLUTION CL OUTP=PRED1;
RUN;

PROC UNIVARIATE DATA=PRED1 NORMAL;
	VAR RESID;
	PROBPLOT RESID /NORMAL(MU=est SIGMA=est);
RUN;

PROC GLM DATA=PRED1;
	CLASS ONCOLOGIST;
	MODEL RESID = ONCOLOGIST;
	MEANS ONCOLOGIST/ HOVTEST=Bartlett;
RUN;

PROC MIXED DATA=MEANS METHOD=TYPE3 COVTEST CL;
	CLASS SUBJECT ONCOLOGIST;
	MODEL VOLUME= ONCOLOGIST/SOLUTION DDFM=SAT CL;
	RANDOM SUBJECT/SOLUTION;
	LSMEANS ONCOLOGIST /CL;
RUN;


PROC MIXED DATA=ANOVA METHOD=TYPE3;
	CLASS F1 … Fk R1 … Rk;
	MODEL Y =  F1 F2 … Fk /SOLUTION DDFM=SAT CL;
	RANDOM R1 R2 … Rk /SOLUTION;
	LSMEANS F1 /CL;
RUN;

